---
- name: "Apache installation and site hosting"
  become: true
  hosts: amazon
  vars:
    apache:
      - httpd
      - mariadb-server
      - mariadb
      - MySQL-python
    http_port: 80
    http_host: wordpress.vyjithks.tk
    http_conf: wordpress.vyjithks.tk.conf
    mysql_root_password: "{{ (lookup('aws_secret', 'keyofmysql', region='ap-south-1') | from_json).mysql_root_password }}"
    mysql_db: wordpress
    mysql_user: wordpress
    mysql_password: "{{ (lookup('aws_secret', 'keyofmysql', region='ap-south-1') | from_json).mysql_password }}"

  tasks:

    - name: "Installing server packages."
      yum:
        name: "{{ apache }}"
        state: present
      tags: apache

    - name: "Enable php74 and epel respositories"
      shell: amazon-linux-extras install php7.4 -y

    - name: "Starting the services"
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - mariadb

    - name: "Copying the website virtual host file to the remote machine"
      template:
        src: httpd.conf.tmpl
        dest: "/etc/httpd/conf.d/{{ http_conf }}"
        owner: root
        group: root

    - name: "Creating apache Document root"
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "apache"
        group: "apache"
